# Tell markdownlint to ignore the following rules

# MD013 - Line length
MD013: false

# MD033 - Inline HTML
MD033: false

# MD034 - Bare URL used
MD034: false

# MD042 - No empty links
MD042: false

# No-emphasis-as-header
MD036: false

# First line in a file should be a top-level header
MD041: false
